name: learnanearnapp
description: "learn an earn"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  cloud_firestore: ^5.0.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  flutter_stripe: ^10.1.1
  http: ^1.2.1
  flutter_dotenv: ^5.0.2
  carousel_slider: ^4.0.0
  file_picker: ^8.0.3
  fluttertoast: ^8.2.6
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false

  assets:
    - assets/
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
