// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl3lcM2l4XX3QSh3fpxLaAkD_22UsEAik',
    appId: '1:609269935347:web:2bac3e1f74775452a05b86',
    messagingSenderId: '609269935347',
    projectId: 'learnanearn-7cbe2',
    authDomain: 'learnanearn-7cbe2.firebaseapp.com',
    storageBucket: 'learnanearn-7cbe2.appspot.com',
    measurementId: 'G-Y38EXD4SN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrrAFtqcGw3E6fa2KlCLUZsQcGMha9GI',
    appId: '1:609269935347:android:96a50a0d318ea132a05b86',
    messagingSenderId: '609269935347',
    projectId: 'learnanearn-7cbe2',
    storageBucket: 'learnanearn-7cbe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApgtUd_RMiUYG6kIySxp0I4qm7sYbWCVY',
    appId: '1:609269935347:ios:3192851366cd2d0ca05b86',
    messagingSenderId: '609269935347',
    projectId: 'learnanearn-7cbe2',
    storageBucket: 'learnanearn-7cbe2.appspot.com',
    androidClientId:
        '609269935347-l59kdh8uavijkhopts79q1t2ea817hh1.apps.googleusercontent.com',
    iosClientId:
        '609269935347-70tit182mi9ca669ocadttvpoan84166.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnanearnapp',
  );
}
